"""Keyboards package exports."""

from keyboards.user import (
    CategoryCallback,
    CouponNavCallback,
    CouponDetailCallback,
    CouponRedeemCallback,
    MyCouponDetailCallback,
    get_main_menu_keyboard,
    get_categories_keyboard,
    get_coupons_paginated_keyboard,
    get_coupon_detail_keyboard,
    get_channels_keyboard,
    get_share_referral_keyboard,
    get_my_coupons_keyboard,
    get_back_to_menu_keyboard,
)
from keyboards.admin import (
    AdminCouponCallback,
    AdminChannelCallback,
    AdminUserCallback,
    AdminNavCallback,
    get_admin_main_keyboard,
    get_admin_coupons_keyboard,
    get_admin_coupon_detail_keyboard,
    get_admin_channels_keyboard,
    get_admin_channel_detail_keyboard,
    get_admin_user_detail_keyboard,
    get_admin_cancel_keyboard,
)

__all__ = [
    "CategoryCallback",
    "CouponNavCallback",
    "CouponDetailCallback",
    "CouponRedeemCallback",
    "MyCouponDetailCallback",
    "get_main_menu_keyboard",
    "get_categories_keyboard",
    "get_coupons_paginated_keyboard",
    "get_coupon_detail_keyboard",
    "get_channels_keyboard",
    "get_share_referral_keyboard",
    "get_my_coupons_keyboard",
    "get_back_to_menu_keyboard",
    "AdminCouponCallback",
    "AdminChannelCallback",
    "AdminUserCallback",
    "AdminNavCallback",
    "get_admin_main_keyboard",
    "get_admin_coupons_keyboard",
    "get_admin_coupon_detail_keyboard",
    "get_admin_channels_keyboard",
    "get_admin_channel_detail_keyboard",
    "get_admin_user_detail_keyboard",
    "get_admin_cancel_keyboard",
]
